apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-29T14:14:55Z"
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "3706"
  selfLink: /api/v1/namespaces/default/services/hello-world-rest-api
  uid: a9e6d6ba-71c7-11ea-817b-42010a8c007d
spec:
  clusterIP: 10.98.2.194
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30354
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.201.182.56
